### ISSUE TITLE
스네이크가 cmd 창 가장자리에 닿으면 스네이크가 복제되어 계속 생성되는 버그

### ISSUE THREAD

**Issue by show43** [show43/snake#1]
기존 소스코드에서 스네이크가  cmd 창 가장자리에 닿으면 스네이크가 복제되어 여러개가 생성되는 버그가 존재합니다.

 스네이크가 벽에 닿으면 게임을 종료시키는 관습적인 규칙을 따라 스네이크가 경계에 부딪히면 게임을 종료시키도록 수정했으면 좋겠습니다.

**Comment by bsh8153** [comment]
배경 보드 추가 됐고 충돌하면
게임 종료가 되도록 수정했습니다.
스네이크가 복제되어 여러개가 생성되는 버그 해결됐습니다.
